# Generated by Django 3.1.2 on 2020-10-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('b_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateTimeField()),
                ('tbl_last_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'Billing',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=120)),
                ('zip_code', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('e_mail', models.CharField(max_length=30)),
                ('hiredate', models.DateTimeField()),
                ('tbl_last_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=120)),
                ('zip_code', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('e_mail', models.CharField(max_length=30)),
                ('tbl_last_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='IcdTable',
            fields=[
                ('icd_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('tbl_last_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'IcdTable',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=120)),
                ('zip_code', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('e_mail', models.CharField(max_length=30)),
                ('tbl_last_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'Lab',
            },
        ),
        migrations.CreateModel(
            name='PatAppointment',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('ap_time', models.DateTimeField()),
                ('tbl_last_dt', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.doctor')),
            ],
            options={
                'db_table': 'PatAppointment',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=120)),
                ('zip_code', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('e_mail', models.CharField(max_length=30)),
                ('member_insurance_id', models.CharField(max_length=30)),
                ('register_date', models.DateTimeField()),
                ('tbl_last_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='NursHmPatient',
            fields=[
                ('p', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='patient.patient')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('tbl_last_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'NursHmPatient',
            },
        ),
        migrations.CreateModel(
            name='OutPatient',
            fields=[
                ('p', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='patient.patient')),
                ('treated_time', models.DateTimeField()),
                ('tbl_last_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'OutPatient',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('treat_type', models.CharField(max_length=30)),
                ('tbl_last_dt', models.DateTimeField()),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patappointment')),
                ('icd_code', models.ForeignKey(db_column='icd_code', on_delete=django.db.models.deletion.DO_NOTHING, to='patient.icdtable')),
            ],
            options={
                'db_table': 'Treatment',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('tbl_last_dt', models.DateTimeField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.hospital')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('rcpt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('payment_amout', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tbl_last_dt', models.DateTimeField()),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.billing')),
            ],
            options={
                'db_table': 'Receipt',
            },
        ),
        migrations.AddField(
            model_name='patappointment',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient'),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=120)),
                ('zip_code', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('e_mail', models.CharField(max_length=30)),
                ('hiredate', models.DateTimeField()),
                ('tbl_last_dt', models.DateTimeField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.hospital')),
            ],
            options={
                'db_table': 'Nurse',
            },
        ),
        migrations.CreateModel(
            name='NonMedicalStaff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=120)),
                ('zip_code', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('e_mail', models.CharField(max_length=30)),
                ('hiredate', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('tbl_last_dt', models.DateTimeField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.hospital')),
            ],
            options={
                'db_table': 'NonMedicalStaff',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_description', models.CharField(max_length=120)),
                ('test_result', models.CharField(max_length=30)),
                ('tbl_last_dt', models.DateTimeField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.lab')),
                ('treat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.treatment')),
            ],
            options={
                'db_table': 'LabResult',
            },
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('ins_p_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('ins_provider_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=120)),
                ('zip_code', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('e_mail', models.CharField(max_length=30)),
                ('tbl_last_dt', models.DateTimeField()),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patappointment')),
            ],
            options={
                'db_table': 'InsuranceProvider',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.hospital'),
        ),
        migrations.AddField(
            model_name='billing',
            name='treat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.treatment'),
        ),
        migrations.CreateModel(
            name='InPatient',
            fields=[
                ('p', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='patient.patient')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('tbl_last_dt', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.room')),
            ],
            options={
                'db_table': 'InPatient',
            },
        ),
    ]
