# Generated by Django 3.1.2 on 2020-10-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20201010_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
